// <auto-generated />
namespace Doctyme.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class openinhour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(openinhour));
        
        string IMigrationMetadata.Id
        {
            get { return "202002140448596_openin hour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
