// <auto-generated />
namespace Doctyme.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDocOrgPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDocOrgPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130234149_Add DocOrgPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
