// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Doctyme.Model
{
    public partial class DoctorGender
    {
        public int DoctorGenderId { get; set; }
        public int GenderTypeId { get; set; }
        public int DoctorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual GenderType Gender { get; set; }
    }

    public class DoctorGenderModel
    {
        public int DoctorGenderTypeId { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        [Range(1, 10, ErrorMessage = "Gender is required")]
        public int GenderTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsViewMode { get; set; }
        public string DoctorName { get; set; }
        public int DoctorId { get; set; }
        public List<GenderType> GendersList { get; set; }
        public bool IsActive { get; set; }
    }
}